import io
P='IRON_ASYLUM_HANDOFF_1_1.md'
s=io.open(P,encoding='utf-8').read()
DIG='''- **Post-V198 tooling pass — no build. `ia-version` stays 198, `index.html` byte-identical throughout.** Five slices, all in `tests/`, run because **B4g would have failed V199 by construction** and a V199 chain would have gone red before grading anything. **A:** `gate.sh` greps `^REFUSED`, echoes it and **exits 1** — Mario ruled a refusal BLOCKS, a claim that did not run is not a pass; same block fixed the detail grep `^FAIL` -> `^[[:space:]]*FAIL`, which had been hiding failure text for **10 of 23** gates. That immediately exposed the coupling nobody had noticed: `g197d`'s E1h refuses on any baseline >= 197, so from V199 it would have refused FOREVER and blocked every chain — re-pointed (not retired) to the new fixed `baselines/V196.html`. **B:** B4g re-expressed from a per-release strict fall to a pinned V197 ceiling (896, WIDE only) plus a non-strict live ratchet; builder disclosed exactly what it widened (one value, 896) and gatekeeper built a D85-revert candidate and proved five other assertions still catch it by name. **C:** E5's digest pin moved out of the baseline branch so `g197d` has mutation coverage for the first time, with an E0 **liveness floor** (`NOBASE_MIN=2`) because E0's lattice claim cannot see anything below itself and a body that died after it used to print a clean shorter `PASS 1`; M7 is a **comment-only** mutation, so only the digest pin can see it. **D:** `g197c`'s `E_POSTERIOR` narrowed to the shipped lens `{hinge, hip_ext}`; Mario ruled that if any assertion moved it was to be REPORTED, not re-pinned — nothing moved, stdout byte-identical on three invocations. **E:** the lens detector, ruled after D proved the narrowing was otherwise **unassertable**: 0 of 2,879 leg cells distinguish the two lenses, so no sweep and no app mutation can ever catch a widening; a hand-built `{Back squat, Leg extension}` card asserted posterior-free is the only detector that can exist, and widening the set reds it alone. GREEN: 23 gates 1322/0, sabotage 179/179 across 20 specs, 18 hunks all under `tests/`, `index.html` 0 hunks. Fuzz explicitly NOT re-run and said so, because the engine provably had not moved. **Also settled this pass:** D88's draw mechanism retracted (the draw picks posterior 99.76% of the time; a pool rule buys 4 weeks), the race-week taper ruled correct by design (746 retired, quote 506), D91 issued for `recoveryDeload`'s push-order arbitration, and the registry line added after three D-code collisions in one session.'''
a='- **V198 — D85, the budget may not spend'
assert s.count(a)==1
s=s.replace(a, DIG+'\n\n'+a)
io.open(P,'w',encoding='utf-8').write(s)
print('digest OK')
