import io
P='IRON_ASYLUM_HANDOFF_1_1.md'
s=io.open(P,encoding='utf-8').read()
def rep(old,new,label):
    global s
    n=s.count(old); assert n==1,'ANCHOR %s count==%d (want 1)'%(label,n)
    s=s.replace(old,new)

NEW='''- **A COPY STRING IS BEING CLASSIFIED AS A BARBELL COMPOUND (V199 measure, latent).** `<svg…> Taper — volume and load pulled back so you arrive fresh.` is handed to `_isCompound` as an item NAME and matches its bare `pull` — inside the word "pulled". **3,072 shipped items.** Latent at the budget (0 guard evaluations on the measured lattice), but the swap-sheet and `swapLoadNote` readers were not measured when this was found, so it may be live there. Same family as `Pallof press` reaching tier 3 through bare `/press/`, and the same family as §12's standing `_isCompound`/`_isIsolation` bare `/lateral/` entry. **Seven other names are flagged by the same sweep** (215-name universe): `Band pull-apart` 6,800 · `Spanish squat hold (KB)` 3,798 · `Pallof press` 3,264 · `Dumbbell renegade rows` 2,895 · `Cable pull-through` 781 · `Power clean (light & explosive)` 166 · `Dumbbell snatch` 42. Only `Pallof press` reaches `return 3`; the first two are caught downstream by `_compoundTier`.
- **`_compoundTier` HAS SEVEN READERS AND ONLY ONE HAS EVER BEEN MEASURED (V199, D89 scope).** A change to tier-3 semantics reaches all of them: `:9558` `capSessionBudget` (the only one measured), `:9684` `capRegionalFatigue` (highest tier per region is the protected compound, so a fall-through name can outrank a real barbell lift and make the wrong item untouchable), `:6441`/`:6456` consecutive-day dedupe (tier distance is the load anchor), `:9083`-`:9087` `swapCandidates`, `:8994` `swapUniverseFor` (sorts tier-descending, so fall-through names head the athlete's list), **`:9097` `swapLoadNote` — ATHLETE-FACING, fabricates "Much lighter than …" on a tier gap of 2**, and **`:13046` the swap sheet UI — ATHLETE-FACING, prints the HEAVY COMPOUND tag on anything `>= 3`, so `Pallof press` carries it in the athlete's hand.** D89 cannot be scoped until the six are measured. Mario ruled: measure them, then coach rules scope.
- **§12's DELETE-THE-GUARD FIGURES WERE PRE-D85 AND ARE SUPERSEDED (V199 measure).** The old 1,080 cells / 410 leg-ish sections / `Zercher` −412 reproduce **exactly on V197** and are wrong for the shipped artifact: on **V198 the same deletion is 949 cells / 270 leg-ish sections**, `Zercher` −70, `Landmine reverse lunge` −136. The ruled D89 fix is far cheaper than deletion — **361 cells (0.38%), 38% of the delete blast radius** — and its two candidate forms (core by SECTION, core by MOVEMENT name) are **byte-identical across all 95,232 cells**; the whole difference is `Pallof press`, which deletion loses 504 of and D89 loses zero of. **Section and item deltas are identical (−268/−250) in EVERY variant while the changed-cell set differs: the guard decides WHO pays, not HOW MUCH.**
- **The tier-3 token share is 28.56%, not 28.81%, and the difference is a method (V199 measure).** The old figure came from walking the whole before-card per trimming cell; **41.32% of tier-3 items sit in sections `_secRank` already protects and the guard never evaluates them.** Of the 10,097 distinct (cell,name) skips the guard actually sees, 2,884 (28.56%) carry a real implement token and 7,213 (71.44%) reach 3 by fall-through. **`Front squat` 2,481 does not reproduce at all** (0 guard evaluations on this lattice), and 784 items (4.4%) between the two card-walk methods are **unexplained** — do not quote either figure without re-deriving it.
'''
rep('## 12. Open / carried forward\n\n','## 12. Open / carried forward\n\n'+NEW,'12')

# D91 is V199, D89 is V200 pending a scope ruling — update the queue
rep("**D89 = V199** (re-source `capSessionBudget`'s tier-3 skip: name core explicitly and make the barbell exemption require an implement token rather than fall through to it — the exemption is asserted by NO gate today) · **D91** (`recoveryDeload` keeps its one surviving accessory block by PATTERN, not by push order — 320 of the 506 zero-posterior weeks, the biggest single lever; 6-8 lines with a card-ORDER constraint, so V200 behind a mandatory counterfactual measure pass) · ",
    "**D91 = V199** (`recoveryDeload` keeps its one surviving accessory block by PATTERN, not by push order — **374 weeks, not the 320 first estimated**; counterfactual printed and clean: 746 -> 372 zero weeks, 374/374 surviving to the shipped card, **0 re-loss at `capRegionalFatigue` and 0 at the budget**, 0 weeks going the wrong way, HALF_MANNY byte-identical, card order preserved in place. 6-8 lines with a card-ORDER constraint and the pre-pass trap: on the **2,166 cards whose Main already carries posterior and no accessory does**, a naive all-sections pre-pass leaves NO accessory block surviving) · **D89 = V200, PENDING A COACH SCOPE RULING** (re-source `capSessionBudget`'s tier-3 skip — but it changes tier-3 SEMANTICS and `_compoundTier` has SEVEN readers, two of them athlete-facing; six are unmeasured) · ",'queue')

# Two labelled numbers, never blurred
rep('**746 is retired as a number. Quote 506.**','**Two labelled numbers, never blurred: 746 is the RAW zero-posterior week count the measures print; 506 is the DEFECT population after excluding the by-design taper weeks. Quote 506 as the problem and 746 as the denominator.**','nums')
io.open(P,'w',encoding='utf-8').write(s)
print('OK')
