import io
P='IRON_ASYLUM_HANDOFF_1_1.md'
s=io.open(P,encoding='utf-8').read()
def rep(old,new,label):
    global s
    n=s.count(old); assert n==1,'ANCHOR %s count==%d (want 1)'%(label,n)
    s=s.replace(old,new)

rep('highest assigned = D91. Next free = D92.','highest assigned = D92. Next free = D93.','reg')
rep('- **Working file:** `index.html` — **V198**; `<meta name="ia-version">`=**198**. Built in order after V197.',
    '- **Working file:** `index.html` — **V199**; `<meta name="ia-version">`=**199**. Built in order after V198.','ver')

# ── §10b ──────────────────────────────────────────────────────────────────────
rep('## 10b. Standing lessons (promoted out of the session digest)\n',
 '''## 10b. Standing lessons (promoted out of the session digest)
- **(V199) A placement spec written against the SOURCE layout can walk a declaration into a gate's confinement slice.** Coach ruled `_isPostChain` be placed "immediately above `recoveryDeload`'s comment block". `g197d` E5's `_itemCost` slice runs from `function _itemCost(` **to that exact comment marker**, so the declaration landed inside a region a gate asserts byte-identical, and builder — following the spec precisely — reddened a confinement with an inert edit. **Before ruling WHERE code goes, grep which digest or byte-identity slices cover the target lines.** The fix was to move it below the marker; a top-level function declaration hoists, so placement was free — but only after something had already gone red to find out.
''','10b')

# ── §11f ──────────────────────────────────────────────────────────────────────
rep('## 11f. Standing decisions — do not re-derive\n',
 '''## 11f. Standing decisions — do not re-derive
### V199 — D91, the deload keeps the pattern the card does not otherwise carry (Mario: "V199 = D91", "Accept")
- **On a deload, the surviving accessory block is the one holding the pattern the card does not otherwise carry (D91).** `recoveryDeload` kept its one block by PUSH ORDER; `Leg superset A` (lunge + knee hold, a unilateral SQUAT pattern) is pushed before `Leg superset B` (the day's hinge), so on every deload leg day the engine kept a SECOND squat-pattern block and deleted the day's only hip extension. Fixed by a pre-pass running the loop's own four classifiers to set `pickIdx`, keyed on the `forEach` index. **374 deload weeks went from zero posterior to zero such weeks**; whole lattice 746 -> 372, 0 weeks going the wrong way.
- **"ADDS NO SETS" MEANS EXACTLY ONE ACCESSORY BLOCK SURVIVES, NOT EQUAL SET COUNT (Mario, V199).** The conservation claim is about BLOCKS — `Leg superset A` + `Leg superset B` == 30,264 in both arms, and per-card block count 79,733 -> 79,733 with 0 gained and 0 lost. The two blocks do not carry equal item counts, so **total working sets CAN fall**: `Leg superset A` [`Walking lunge (KB)` 4x8-12, `Wall sit` 4x25 sec] becomes `Leg superset B` [`Barbell Romanian deadlift` 4x6-10], **8 working sets to 4**, on 2,427 of 134,946 cards. Coach ruled that coaching-correct — lower volume is the point of a deload week — and it is NOT a licence to quote "adds no sets" as a volume guarantee.
- **Arbitrated correctly, the deload PROTECTS the posterior chain rather than deleting it (V199).** The counterfactual beats switching the pass off entirely: shipped deload zero-posterior weeks **0**, `__DELOAD_OFF` **40**. Deleting the pass leaves forty deload weeks with no hip extension, because the full card walks into `capRegionalFatigue` and the cap eats the hinge; the slimmed card gives the regional cap less to spend.
- **The 60 residual killed days are a deliberate BOUNDARY, not debt (D91).** They are `Explosive finisher` days where the only posterior is a ballistic conditioning item and the survivor is `Strength`. Not one lands a week on zero. Reaching them would mean promoting a conditioning finisher onto a deload card, which runs Mario's own deload ruling backwards ("recovery week = main lift + ONE accessory block + hip prehab, nothing else"). Pinned at exactly 60 BY LABEL so a future widening into `optional`/fluff reds a gate.
- **The race-week taper is correct by design, and the two numbers stay labelled (V199).** 240 of the raw 746 zero-posterior weeks are W13/W14 on `goal=half`. A hinge in W14 would VIOLATE D37/D38. **746 is the RAW count, 506 the DEFECT population** — quote 506 as the problem and 746 as the denominator, never one for the other.
- **D88's draw mechanism was measured and RETRACTED (V199).** The `legIso` pool held a posterior member 10,080/10,080 draws and the draw PICKED one 10,056/10,080 (99.76%). A pool-side rule reaches 146/746 weeks and realises 746 -> 742. D88 survives as an OBSERVATION, not a mechanism, and is low priority.

''','11f')

# ── §12 ───────────────────────────────────────────────────────────────────────
NEW='''- **D92 — A POST-BUILD RENAMER REWRITES ITEMS AFTER `capSessionBudget`, AND IT COSTS 108 CELLS THEIR POSTERIOR LABEL (V199 gatekeeper, ACCEPTED by Mario, unbuilt).** Of D91's 2,160 newly-surviving cells, 108 reach the shipped card with no posterior left and **not one loses it to a trim** — a renamer rewrites the item after the budget, **all on the bodyweight tier**. **0 of the 108 leave their week without posterior**, so D91's week-level claim holds and this is a pre-existing rename-surface defect that D91 merely made visible. Disclosed by the gate itself (`I2`/`I2b`/`I2c`/`I2d`), not papered over.
- **NEXT TOOLING PASS (V200), ITEM 1 of 4 — the pull A/B swap ships with ZERO gate coverage.** D91 says "by PATTERN", not "on leg days", so it also swaps `Pull superset A/B` (606 differences on gatekeeper's wider lattice, `Kettlebell swing` the posterior item). It is exactly conservative — Pull A+B 30,592 -> 30,592 — but coach's anti-keep-both assertion F3 is Leg-only. **ADD a per-card surviving-block-count identity ALONGSIDE F3, never replacing it**: F3's hand-pinned 30,264 is an independent oracle and a count identity is the weaker claim. Gatekeeper's general form already measures 79,733 -> 79,733, 0 gained, 0 lost, 4,509 swapped.
- **NEXT TOOLING PASS (V200), ITEM 2 of 4 — WORKING SETS ARE COUNTED BY NO ASSERTION IN THE SUITE.** Every assertion counts blocks or posterior ITEMS. The 8-sets-to-4 deload volume drop is therefore **invisible by construction**, and D91's volume audit is its only coverage. **Decide whether a set-count assertion belongs in `g199` or stays with the audit.**
- **NEXT TOOLING PASS (V200), ITEM 3 of 4 — `g193_budget_floor` B3 should REFUSE on an unsupported baseline pair, not fail.** `V198-vs-V196` reads `PASS 34 FAIL 2` and has since D85 shipped: both licences key to the immediate predecessor (`'197'`, `'198'`), a V196 baseline disarms both and the bare ratchet is known-red by ruling. Gatekeeper re-derived it against `git show HEAD:` and agrees it is an **unsupported invocation, not a broken gate** — widening the key to "any older baseline" would turn an expiring licence into a permanent carve-out. Give it E1h's shape: a named, loud refusal that `gate.sh` already blocks on.
- **NEXT TOOLING PASS (V200), ITEM 4 of 4 — B5c wants a redesign; it has moved three releases running (240 -> 235 -> 187).** Every duplicate it has EVER counted is `Step-ups (KB)`, on one tier family. Coach's recommendation: rebuild as a **per-name ceiling on `Step-ups (KB)` plus a hard zero elsewhere**. A real improvement, but a gate redesign that must not ride along inside a re-pin.
'''
rep('## 12. Open / carried forward\n\n','## 12. Open / carried forward\n\n'+NEW,'12')

# queue: D91 built, D92 added
rep("Queue, ALL RULED AND CONCURRED, none built: **D91 = V199** (",
    "**V199 BUILT D91.** Queue, ALL RULED AND CONCURRED, none built: **D92** (a post-build renamer rewrites items after `capSessionBudget` and costs 108 cells their posterior label, bodyweight only; 0 of the 108 leave their week without posterior, so it is a rename-surface defect D91 made visible, accepted at V199) · **D91 — BUILT AT V199** (",'queue')

# ── digest ────────────────────────────────────────────────────────────────────
DIG='''- **V199 — D91, the deload stops deleting the day's only hip extension.** `recoveryDeload` kept its one surviving accessory block by PUSH ORDER, and `Leg superset A` (lunge + knee hold, a unilateral SQUAT pattern) is pushed before `Leg superset B` (the hinge) — so on every deload leg day the engine kept a second squat-pattern block and deleted the day's only hip extension. Coach ruled it, then **refused to sign until someone printed the realised week count**. The counterfactual came back cleaner than it dared assume: **374 deload weeks flip and all 374 survive to the shipped card**, 0 lost at `capRegionalFatigue` and 0 at the budget against a feared 5.3%; whole lattice **746 -> 372**, **0 weeks going the wrong way**; and the fix **beats switching the deload off entirely** (0 deload zero-weeks against 40), because a slimmed card gives the regional cap less to spend. Coach also corrected its own headline number unprompted — it ruled 320, the measure said **374**. Three gates went red on the candidate and **every one was a confinement built the session before, firing correctly on its first real edit**: B3's D85 licence **self-expired on schedule** and the bare ratchet ran; E5's digest pin caught the `_isPost` alias; B5c caught 48 released duplicates. The fourth red was ours — **coach's placement spec walked the hoisted declaration into E5's `_itemCost` slice**, which is now a §10b lesson. All four closed: a D91 displacement licence (equality, sum 399, four names, zero residual, self-expiring at V200), B5c re-pinned 235 -> 187 as an equality with all 48 instances named, E5 re-pinned behind an era predicate that still trips on a comment-only edit. GREEN: 24 gates **1378/0**, 0 REFUSED, sabotage **8/8** on v199 and **179/179** elsewhere, 5 hunks 100% classified with 0 unruled removals, fuzz 2,916 configs / 16,991 differing cells / 0 unclassified. `HALF_MANNY` byte-identical at `6e32421331693437` — Mario's deload leg days take the runner branch, one combined circuit that already carries the hinge, so D91 is invisible to him and fixes it for everyone on the A/B pair. **Disclosed and accepted, not hidden:** 108 of the 2,160 lose their posterior label to a **post-build renamer** (bodyweight only, 0 leave their week without posterior) — filed as **D92**; the **pull A/B swap ships with no gate coverage**; and **no assertion in the suite counts working sets**, so the 8-sets-to-4 deload drop is invisible by construction.'''
a='- **Post-V198 tooling pass — no build.'
assert s.count(a)==1
s=s.replace(a,DIG+'\n\n'+a)
io.open(P,'w',encoding='utf-8').write(s)
print('handoff OK')
