'use strict';
const path=require('path');const H=require('/Users/CanasBangin/Desktop/TheBig6V2/tests/harness.js');const S=process.env.SCR;
const clone=x=>JSON.parse(JSON.stringify(x));const clean=n=>String(n==null?'':n).replace(/<svg[\s\S]*?<\/svg>\s*/g,'').replace(/<[^>]+>/g,'').trim();
const live=d=>(d&&!d.rest&&d.sections||[]).filter(s=>(s.items||[]).length);const card=d=>live(d).map(s=>clean(s.label||s.coreHeader||'')+(s.superset?' (SS '+(s.rounds||'')+')':'')+' :: '+s.items.map(it=>clean(it.name)+' '+clean(it.detail||'')+(it.__bw?' [<'+it.__bw.was+']':'')).join(' | ')).join('\n      ');
const T={};const vm=t=>{if(T[t])return T[t];const X=H.load(path.join(S,'t_'+t+'.html'));const TT=new Date('2026-08-24T12:00:00').getTime();const RD=Date;class FD extends RD{constructor(...a){if(a.length)super(...a);else super(TT);}static now(){return TT;}}X.ctx.Date=FD;return T[t]=X;};
const build=(t,c,fl)=>{const X=vm(t);(fl||[]).forEach(f=>X.ctx[f]=true);let p;try{p=X.buildProgram(clone(c));}finally{(fl||[]).forEach(f=>{delete X.ctx[f];});}return p;};
const M={name:'M',primaryPath:'lift',cardioTypes:[],cardioGoals:{},eventTargeted:false,raceDate:null,liftingFocus:'support_prevention',experience:'intermediate',ageBracket:'18-35',equipment:'bodyweight',unit:'lbs',restDays:['sun','wed'],days:H.DAYS.slice(),bench:135,squat:155,deadlift:185,seed:76308,injury:{region:'ankle',tier:'protect'}};
// INJ cell: support_prevention|test|bodyweight|ankle/protect|intermediate|s76308|sun,wed  -> test fam: run_pace_goal or run_base; find by rebuilding M17's INJ enumeration
const FOC=['hypertrophy','strength','fatloss','balanced','support_strength','support_athletic','support_prevention'],FAM={race:[['run_5k',{}],['run_10k',{}],['run_half',{}],['run_marathon',{}]],test:[['run_pace_goal',{targetDist:'1.5',targetMins:'10',targetSecs:'30'}],['run_base',{}]],none:[[null,{}]]},TIERS6=['commercial','crossfit','home_full','home_basic','minimal','bodyweight'],EXPS=['beginner','intermediate','advanced'],SEEDS=[87747,76308,1234,4242],RESTS=[['sun','wed'],['sat','sun']],REGS=['knee','ankle','hip','lowback','shoulder','elbow'],ITIERS=['workaround','protect'];
function mk(f,fam,eq,ei,si,ri,inj){const g=FAM[fam][(si+ei)%FAM[fam].length];const c={name:'M',primaryPath:/^support_/.test(f)?'event':'goal',cardioTypes:g[0]?['run']:[],cardioGoals:g[0]?{run:Object.assign({id:g[0],label:g[0],mileBestMins:'8',mileBestSecs:'0',baselineDist:'3',baseline:'3mi'},g[1])}:{},eventTargeted:false,liftingFocus:f,experience:EXPS[ei],ageBracket:'18-35',equipment:eq,unit:'lbs',restDays:RESTS[ri].slice(),days:H.DAYS.slice(),bench:135,squat:155,deadlift:185,seed:SEEDS[si]};if(inj)c.injury=inj;return c;}
let k=0,INJ=null;for(const r of REGS)for(const t of ITIERS)for(const f of FOC)for(const fam of Object.keys(FAM))for(const eq of TIERS6)for(let ri=0;ri<2;ri++){const ei=k%3,si=(k>>1)%4;k++;if(r==='ankle'&&t==='protect'&&f==='support_prevention'&&fam==='test'&&eq==='bodyweight'&&ri===0&&EXPS[ei]==='intermediate'&&SEEDS[si]===76308)INJ=mk(f,fam,eq,ei,si,ri,{region:r,tier:t});}
console.log('=== W5-step circuit ops, ankle/protect bodyweight prevention');
for(const [name,c,days] of [['INJ test intermediate s76308 sun,wed (goal '+(INJ&&INJ.cardioGoals.run.id)+')',INJ,[[3,'thu'],[9,'thu']]],['L432 none beginner s76308 sun,wed',Object.assign(clone(M),{experience:'beginner'}),[[3,'thu'],[4,'thu']]]]){if(!c){console.log('  (cell not found) '+name);continue;}
  console.log('\n--- '+name);const PA=build('ABx',c),PP=build('PREx',c),PR=build('PREx',c,['__REGIONAL_OFF']),PB=build('PREx',c,['__BUDGET_OFF']);const X=vm('ALLxs');X.eval('globalThis.__PRE=null');const PF=X.buildProgram(clone(c));const pre=JSON.parse(X.eval('globalThis.__PRE'));X.eval('globalThis.__PRE=undefined');
  for(const [w,d] of days){const dy=t=>t.weeks[w]&&t.weeks[w][d];console.log('  W'+w+' '+d+(dy(PA).cardio?' {'+(dy(PA).cardio.subtype||dy(PA).cardio.type)+'}':' {dry}')+'\n    [ABx final]      '+card(dy(PA))+'\n    [PREx final]     '+card(dy(PP))+'\n    [PREx regional-off] '+card(dy(PR))+'\n    [PREx budget-off]   '+card(dy(PB))+'\n    [ALLx pre-sweep snapshot] '+card(pre[w][d])+'\n    [ALLx final]     '+card(dy(PF)));}}
console.log('\n=== A-2(drop) example: FULL support_prevention|none|commercial|none|beginner|s1234|sun,wed W3 thu, B vs ABx (+ablations)');
const c2=mk('support_prevention','none','commercial',0,2,0,null);for(const [t,fl] of [['B',[]],['ABx',[]],['ABx',['__REGIONAL_OFF']],['ABx',['__BUDGET_OFF']]]){const p=build(t,c2,fl);console.log('  ['+t+(fl.length?' '+fl[0]:'')+'] '+card(p.weeks[3].thu));}
